theme: jekyll-theme-slate
title: Dwarf Fortress Localization Project
description:
show_downloads:
google_analytics: G-DNMLX4Z270
yandex_metrika: 68992363
yandex_verification: 8507648c14efec96
github:
  zip_url: http://example.com/download.zip
  another_url: another value
  is_project_page: "true"
  repository_url: https://github.com/dfint
