theme: jekyll-theme-slate
title: Dwarf Fortress Localization Project
description: Dwarf Fortress localization project official site
show_downloads:
google_analytics: G-DNMLX4Z270
yandex_metrika: 68992363
yandex_verification: 8507648c14efec96
google_site_verification: 0lZ2eOgznBEIVtkL95dRRJgNHxW8muvlKyJ0WveueZQ

github:
  zip_url: http://example.com/download.zip
  another_url: another value
  is_project_page: "true"
  repository_url: https://github.com/dfint

production_url: https://dfint.github.io

plugins:
  - jekyll-redirect-from
